### ISSUE TITLE
Consider using _.merge (or similar pattern) for nested options instead of _.extend

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/phet-info#91] opened 2019-01-29 23:36 UTC
After an unexpectedly lengthy thread in Slack, it seemed like this was worth discussing at the dev meeting.

While working on phetsims/scenery-phet#451 and implementing the nested options pattern outlined in https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md#nesting, I realized that Lodash has a `merge` function that has similar functionality to `_.extend` though can also extend nested objects.

```js
function MyNodeTypeWithHSliderInIt( options ) {

    options = _.merge( {
      visible: false,
      pickable: false,
      
      hsliderOptions: {
        endDrag: function() { console.log( 'Drag Ended') }, 
        startDrag: function() { console.log( 'Drag Started') }
      }
    }, options );
  
    var slider = new HSlider( new Property(), new Range(), options.hsliderOptions );
  }
```

If the client overwrites `hsliderOptions.startDrag` and adds `hsliderOptions.ariaValueTextPattern = somePatternString`, those changes will all be correctly passed to the HSlider constructor without an additional call to `_.extend`.

However, 2 concerns arise from this function:
1. it mutates the first argument (same behavior as `extend`, so if a reference to a default object were passed in (`_.merge( defaultOptions, otherOptions )`), `defaultOptions` would have the new/updated keys added. From Slack, @samreid  noted that this can be solved with

> A note, we may typically need to do `_.merge({}, DEFAULTS, {other things})` so we don’t mess up the `DEFAULTS`

2. Unlike `_.extend`, `_.merge` performs a deep copy of the objects. Developers noted that this is a problem for situations like Enumerations where the actual reference is important.

@jonathanolson 
> Merge sounds like it would prevent us from being able to pass plain JS objects through. For instance... enumeration values
> sounds like it would mutate the name of enumeration values as currently written.

> `_.merge( {}, { repr: Repr.PIE } ).repr === Repr.PIE` // false

or
 
```js
const obj = _.merge( {}, { nodeOption: nodeOpt, A: enumOpt.A } );
Object { nodeOption: {…}, A: {…} }
obj.A === enumOpt.A;
false
obj.nodeOption === nodeOpt
true
```

So there are 

@samreid mentioned
> If we like the idea of merge, but lodash isn’t a perfect fit, we could create PHET_CORE/merge however we like.

@jonathanolson 
> `merge( /*start template*/ { subopts: {} } /*end template*/, { subopts: { a: 5 } }, { subopts: { b: 2 } } )`

**Comment by samreid** [comment] 2019-01-30 03:38
So the main point is we like the recursion, but we need control about how deep the recursion should go?  And for `Enumeration`s we can maybe control the depth of recursion with `freeze` but we have no way to control the depth of recursion with, say, `Node`?

**Comment by mbarlow12** [comment] 2019-01-30 23:46
> For instance, it only recurses into sub-objects that end in the suffix options, like sliderOptions.
This seems like a nice pattern. I'm starting to lean towards a `PHET_CORE/Merge` solution. That option could also potentially allow developers to omit the nested object keys. e.g.
```js
options = Merge.merge( { defaults }, options ); // or options = new Merge( defaults, options );
options.getFlat() // options with nested keys omitted (or something like Merge.removeNestedOptions( options );
```

**Comment by pixelzoom** [comment] 2019-01-31 02:54
To evaluate the example in https://github.com/phetsims/phet-info/issues/91#issue-404535227, we should see what it looks like with our current `_.extends` pattern, so see below.  In general, the default for each set of nested options is filled in with an additional `_.extend` call.   I haven't had the need to nest more than 1 level deep yet, but I suppose that could be encountered.

```js
function MyNodeTypeWithHSliderInIt( options ) {

    options = _.merge( {
      visible: false,
      pickable: false,
      hsliderOptions: null // nested options passed to HSlider, set below
    }, options );

    options.hSliderOptions = _.extend( {
        endDrag: function() { console.log( 'Drag Ended') }, 
        startDrag: function() { console.log( 'Drag Started') }
    }, options.hSliderOptions,  );
  
    var slider = new HSlider( new Property(), new Range(), options.hsliderOptions );
  }
```

**Comment by jonathanolson** [comment] 2019-01-31 17:01
I'll definitely clarify any potential objections during the dev meeting, but it seems workable to only recurse into keys that end in `Options`. The example would be:

```js
constructor( options ) {

  options = merge( {
    visible: false,
    pickable: false,
    hSliderOptions: {
      startDrag: () => {},
      endDrag: () => {}
    }
  }, options );

  const slider = new HSlider( new Property(), new Range(), options.hsliderOptions );
}
```
where we would use our own import (`PHET_CORE/merge`), and the nested options would not need to be separated out.

**Comment by mbarlow12** [comment] 2019-01-31 18:59
Another element to consider is that when nested options are used in a base type, the pattern @pixelzoom illustrated in https://github.com/phetsims/phet-info/issues/91#issuecomment-459195618 has to be propagated to subtypes and potentially suptype instantiations. For example, if my sim creates a type that uses `MyNodeTypeWithHSliderInIt`

```js
function MyNodeThatNeedsNestedOptions( options ) {

    options = _.merge( {
      visible: false,
      pickable: false,
      nodeWithHSliderInItOptions: null
    }, options );

    var nodeWithHSliderInItOptions = _.extend( {
      hSliderOptions: null,
      maxWidth: 44,
      ...
    }, options.nodeWithHSliderInItOptions );
    
    nodeWithHSliderInItOptions.hSliderOptions = _.extend( {
      endDrag: function() { ... }, 
      startDrag: function() { ... }
    }, nodeWithHSliderInItOptions.hSliderOptions );
  
    var nodeWithHSliderInIt = new MyNodeTypeWithHSliderInIt( new Property(), new Range(), nodeWithHSliderInItOptions );
  }
```
this also doesn't show the issue if there are 2 instantiations of `MyNodeThatNeedsNestedOptions` that each have different start/end drag functionality.

**Comment by pixelzoom** [comment] 2019-02-14 20:01
2/14/19 dev meeting consensus:

* @mbarlow12 will implement
* Recurse only into keys with `Options` suffix
* assert that the the value doesn't have `prototype`.

**Comment by mbarlow12** [comment] 2019-02-19 05:38
I've added the merge function and a large number of unit tests, but it's possible I've missed some cases to check.

Thus far, it seems to be working well but explicitly checking the key for 'Options' as well as testing that it's prototype is the same as `Object`. It will also throw an assertion error if the `...Options` key holds anything other than a brace-style object (e.g. `someNestedOptions: {...}`). Thus, if we wanted to set the nested options with a function
```js
someNestedOptions: function() {
  return {
    key: 'value'
  };
}
```
that will currently fail, too.

One departure from `_.merge()` is that I'm not handling/merging arrays that contain objects. They are currently treated as any other key. I don't recall exactly how frequently arrays appear in our options, but the following scenario is a little tricky:
```js
const o1 = {
  subOptions: {
    arr: [
      {
        moreOptions: {
          key1: 'val',
          key2: 'val2'
        }
      },
      { key4: 'val4' }
    ]
  }
};

const o2 = {
  subOptions: {
    arr: [
      {
        moreOptions: {
          key1: 'new val',
          key3: 'another'
        }
      },
      { key3: 'value3' }
    ]
  }
};

const o3 = merge( o1, o2 );
```
lodash's implementation would result in 
```js
o3 = {
  subOptions: {
    arr: [
      {
        moreOptions: {
          key1: 'new val', 
          key2: 'val2', 
          key3: 'another'
        }
      },
      {
        key4: 'val4',
        key3: 'value3'
      }
    ]
  }
}
```
and is dependent on the order in the array.

**Comment by samreid** [comment] 2019-03-18 17:01
I have case in Wave Interference where it would be appropriate to use merge (I think), however, it seems like merge is mutating the arguments.  It's unclear whether this is desirable.

For instance:
```js
    const a = {
      sliderOptions: {
        hello: 'there'
      }
    };
    const b = {
      sliderOptions: {
        time: 'now'
      }
    };
    merge( {}, a, b );
```

results in 
```
JSON.stringify(a,null,2)
"{
  "sliderOptions": {
    "hello": "there",
    "time": "now"
  }
}"
```

Is that as expected?  What I'm seeing in Wave Interference is that `"units: 'nanometers'"` is getting injected into `NUMBER_CONTROL_OPTIONS` and used in places that shouldn't have `"units: 'nanometers'"`.

I'm not sure whether I should tinker with `merge` or do something simulation-specific until we discuss/address this.

**Comment by pixelzoom** [comment] 2019-03-18 17:16
`merge` is clearly modifying the value of its `options` argument:

```js
  function merge( obj ) {
     ...
    return obj;
  }
```


That violates best practices for options (see https://github.com/phetsims/phet-info/issues/96), and is likely why `NUMBER_CONTROL_OPTIONS` (which is presumably intended to be a constant) is being modified.

**Comment by pixelzoom** [comment] 2019-03-18 17:23
On the other hand, maybe `merge` is intended to work like `_.extend`.   If that's the case, then @samreid's workaround in https://github.com/phetsims/wave-interference/commit/3f3d173a4e6dc882f06f4d2aae4d10ce8c68b18a is actually the correct way to do this.

`const merged = merge( {}, options, NUMBER_CONTROL_OPTIONS );`

**Comment by pixelzoom** [comment] 2019-03-18 17:24
On the other hand, maybe `merge` is intended to work like `_.extend`, and modify it's first arg.   Hard to tell without documentation.  But if that's the case, then @samreid's workaround in https://github.com/phetsims/wave-interference/commit/3f3d173a4e6dc882f06f4d2aae4d10ce8c68b18a is actually the correct way to do this.

`const merged = merge( {}, options, NUMBER_CONTROL_OPTIONS );`

**Comment by pixelzoom** [comment] 2019-03-18 17:26
Hmmm... @samreid originally had something like:

`merge( {...}, NUMBER_CONTROL_OPTIONS ) );`

... and reported that `NUMBER_CONTROL_OPTIONS` was being modified. Do I have that right? If so, there are bigger problems here.

**Comment by pixelzoom** [comment] 2019-03-18 17:28
Imo, the unit tests in `mergeTests.js` are inadequate.  They do not verify that objects that should not modified are unchanged after a `merge`.

**Comment by pixelzoom** [comment] 2019-03-18 17:30
Are the unit tests in mergeTests.js adequate? Do they verify that objects that should not be modified are unchanged after a merge?

**Comment by samreid** [comment] 2019-03-18 17:32
> Do I have that right? If so, there are bigger problems here.

I had this code:

```js
      super( title, property, property.range, merge( {
        sliderOptions: {
          majorTicks: [ {

            // TODO: model coordinates for these
            value: property.range.min,
            label: new WaveInterferenceText( minLabel )
          }, {
            value: property.range.max,
            label: new WaveInterferenceText( maxLabel )
          } ]
        }
      }, NUMBER_CONTROL_OPTIONS, options ) );
```

And it was modifying `NUMBER_CONTROL_OPTIONS`.  If I switch the order to:

```js
}, options, NUMBER_CONTROL_OPTIONS ) );
```

Then it works correctly, but options gets mutated.

**Comment by samreid** [comment] 2019-03-18 17:35
One more point for code review.  We discussed merging for keys that end with `Options`, but the implementation looks like it is instead checking `prop.includes( 'Options' )`

**Comment by pixelzoom** [comment] 2019-03-18 17:40
Documentation for `merge.js` does not pass code review.  I've add TODOs to the code.

**Comment by pixelzoom** [comment] 2019-03-18 17:41
All args expect the last one are modified because `merge` is calling itself recursively:

`31 Object.defineProperty( obj, prop, merge( obj[ prop ], source[ prop ] ) );` 

This is a problem.  And yes, it means the unit tests are inadequate.  Recommended not to use `merge` until this is fixed.

**Comment by pixelzoom** [comment] 2019-03-18 17:43
Hmm... Or again, is this intended behavior?  Hard to tell without documentation.

**Comment by pixelzoom** [comment] 2019-03-18 17:43
Hmm... Or again, is this intended behavior? Hard to tell without documentation. I'm not going to do any more work on this until @mbarlow12 has had a chance to chime in.

**Comment by pixelzoom** [comment] 2019-03-18 17:47
I expected behavior like `._extend`, where only the first arg is modified.  E.g.:

```js
> var a = { a: 1, b: 2 }
> var b = { c: 3, d: 4 }
> _.extend( a, b, { e: 5, f: 6 } )
> a
{a: 1, b: 2, c: 3, d: 4, e: 5, f: 6 }
> b
{c: 3, d: 4}
```

**Comment by pixelzoom** [comment] 2019-03-18 17:49
FYI, `_.merge` behaves identically to `_.extend`, it only modifies its first arg, see below.  So merge.js is not "Like LoDash's _.merge".

```js
> var a = { a: 1, b: 2 }
> var b = { c: 3, d: 4 }
> _.merge( a, b, { e: 5, f: 6 } )
> a
{a: 1, b: 2, c: 3, d: 4, e: 5, f: 6 }
> b
{c: 3, d: 4}
```

**Comment by mbarlow12** [comment] 2019-03-19 19:15
`merge` was intended to work exactly like `_.merge`. I believe the issue will be fixed by recursing with
```js
Object.defineProperty( obj, prop, merge( obj[ prop ], source[ prop ] ) );
```
I'll add unit tests that create copies of 2nd and 3rd args and ensure they're the same after calling merge.

**Comment by mbarlow12** [comment] 2019-03-19 21:25
After a little review, I'd like to know more about how @samreid's options are being mutated. I'd also already written the unit tests to check that args 2, 3, ... aren't modified, so I'd like to know what those missed.

The function iterates over each of the desired sources and recurses separately into each if/when appropriate. The `obj` reference always comes from the first argument to `merge` and never from one of the `source` objects. Thus `Object.defineProperty( obj, prop, merge( obj[ prop ], source[ prop ] ) );` should still be ok.

**Comment by pixelzoom** [comment] 2019-03-19 21:31
> ... should still be ok.

Verified:

```
> var a = { a: 1, b: 2 }
> var b = { c: 3, d: 4 }
> phet.phetCore.merge( a, b, { e: 5, f: 6 } )
> a
{a: 1, b: 2, c: 3, d: 4, e: 5, f: 6 }
> b
{c: 3, d: 4}
```

@mbarlow12 and @samreid should probably discuss.

**Comment by mbarlow12** [comment] 2019-03-19 22:53
I've realized that this presents a pretty tricky issue when considering objects like Enumerations and Properties.

From @samreid's comment: https://github.com/phetsims/phet-info/issues/91#issuecomment-474008231,
```js
    const a = {
      sliderOptions: {
        hello: 'there'
      }
    };
    const b = {
      sliderOptions: {
        time: 'now'
      }
    };
    merge( {}, a, b );
```
the issue comes from
`Object.defineProperty( obj, prop, Object.getOwnPropertyDescriptor( source, prop ) );` 
where a reference to `a.sliderOptions` is copied onto the empty object from the first argument (target). Thus, merging `b` mutates a reference to `a.sliderOptions` resulting in undesired behavior.

One solution is to create a copy of each source's `...Options` object. While this solves the behavior above, it does not retain references to Enumerations and Properties which is why we're making our own implementation over `_.merge`.

This leads to a pretty significant problem given the following scenario:
```js
    const a = {
      sliderOptions: {
        enumOpt: someEnum.VALUE
      }
    };
    const b = {
      sliderOptions: {
        enumOpt: anotherEnum.ANOTHER_VALUE
      }
    };
    const obj = merge( {}, a, b );
```
From https://github.com/phetsims/phet-info/issues/91#issue-404535227, @jonathanolson would like references to be copied such that `obj.sliderOptions.enumOpt === b.sliderOptions.enumOpt //true` (please correct me if I'm mistaken in this). If this is the case, then any sort of merging will mutate prior arguments (e.g. `a.sliderOptions.enumOpt === b.sliderOptions.enumOpt`), and the only solution would be to dereference the key in question on `obj` and recopy.

**Comment by samreid** [comment] 2019-03-20 14:32
Updated labels to mark for developer meeting.  @mbarlow12 let me know if this is incorrect.

**Comment by mbarlow12** [comment] 2019-03-20 15:41
@samreid thanks, I'd meant to do that. I reverted to the original `merge` implementation since this is still in discussion.

**Comment by mbarlow12** [comment] 2019-03-21 18:23
If we want to go with the dereferencing option, it'd useful to know what types should have references copied.

**Comment by pixelzoom** [comment] 2019-03-21 18:56
Verified that `b` is not modified in this case:

```
> var a = { a: 1, b: 2 }
> var b = { c: 3, d: 4 }
> phet.phetCore.merge( a, b, { d: 5, e: 6 } )
> a
{a: 1, b: 2, c: 3, d: 5, e: 6}
> b
{c: 3, d: 4}
```

**Comment by samreid** [comment] 2019-03-21 19:02
@jonathanolson and @zepumph volunteered to meet with @mbarlow12 for investigation.

**Comment by kathy-phet** [comment] 2019-03-21 19:41
Hi guys - This thread seems to be consuming quite a bit of developer bandwidth (from an observer perspective), and I wanted to check in to see if this is a problem worth consuming more developer time and addressing right now, given all the other priorities and things we are trying to tackle. I welcome reflections. Thanks!

**Comment by samreid** [comment] 2019-03-22 00:02
This will be a valuable part of our code and an improvement over the current brittle strategy.  I recommend @jonathanolson @zepumph and @mbarlow12 to investigate further and report back after their meeting.

**Comment by zepumph** [comment] 2019-06-28 18:45
Status on this issue from what I see. I don't think that I was involved in any further work with this. @jonathanolson did you meet with MB?

Even so, I see that `merge` is used in wave-interference, and the intro version is soon to be published. I'm unsure what needs to happen here to make this production worthy, or at least it would be good to get on the same page about it's usability. Marking for dev meeting.

Note that I see 82 usages of extending nested option below in another extend call (using regex `[a-z]+Options: null,`).

**Comment by samreid** [comment] 2019-06-28 22:24
@zepumph volunteered to review merge and its usages and unit tests.  That will put us in a better position to understand what the next steps are.

**Comment by samreid** [comment] 2019-06-29 02:19
Also, in review @chrisklus and @zepumph and I looked at code with `merge` and without `merge` and agreed `merge` is so much nicer it is worth the trouble to get it into the mainstream.

**Comment by zepumph** [comment] 2019-07-03 00:49
From the review:

* Should we allow this case?

```js

options = _.extend( {
  xOptions: null // filled in below
  . . . 
}, options );
options =  merge( { 
  xOptions: { test: 1 } 
}, options );
```
Since xOptions, is null it fails the type check validation. I ran into this in a pattern in `INVERSE_SQUARE_LAW_COMMON/ISLCObjectNode` and `NumberControl`. Where it is nice merge after an extend call so the merge can use some of the parent options. I think we may want to either set to an empty object, or just omit this nested options object from the original extension.

* > // TODO phet-info#91 by calling recursively, this mutates all except the last arg. Should only mutate the first arg, ala _.merge and _.extend.

  I could not find any spot where we were mutating anything except the final target (first arg). There are also a few tests confirming this. I'm going to remove this todo.


* Currently merge supports a nested options field called `Options: {}` with no prefix. Should we support this?

Review is complete. It would be nice to discuss these points out with someone, though I'm not really sure who. We could discuss at developer meeting but that seems more costly than needed. @ariel-phet will you please assign someone to look over my review before bringing this to developer meeting.

**Comment by zepumph** [comment] 2019-07-30 16:11
In the above commit I added support for optional options objects to be passed as sources. I also added tests for that. Basically it works by ignoring any source that is `undefined`, but it would assert out if a source was `{null|string|number|etc}`.

**Comment by zepumph** [comment] 2019-08-08 19:18
From developer meeting today

>Should we allow this case?


No we don't allow that case, `*Options` values must be objects.

> How to handle options used in other options:

Have an extend call first which merge all options used in other options, and then use those in the below merge.

```
  // options used in options set below
  options = _.extends( {
        tickLabelFont: new PhetFont( 12 )
      }, options );

   options = merge( {
      sliderOptions: {
        majorTicks: [
          { value: range.min, label: new Text( range.min, { font: options.tickLabelFont } ) },
          { value: range.max, label: new Text( range.max, { font: options.tickLabelFont } ) }
        ]
      }
  }, options );
```



* rename: `mergeOptions`, `mergePhetOptions`, `phetMerge`. Something that should be clear that merge is only recursive for '*Options' keys. Straw poll indicates `mergeOptions` is the winner.

* replace all usages of `_.extends` with our merge library? We considered this, and think it should probably be done at some point in the future. It will decrease the cognitive load of options to only have one way of doing things, instead of two, similar but different ways to be used in different cases.  Not right now though. Let's wait until we have used it more thoroughly and our merge library very very vetted. Are there performance considerations?


>Currently merge supports a nested options field called Options: {} with no prefix. Should we support this?

* `Options` as a key is not allowed. Make that error out

* assert that option keys are named with a lowerCase? No need, thanks though.

**Comment by zepumph** [comment] 2019-09-09 23:53
Alright the above has been implemented. As per the discussion in developer meeting from August 8th, merge is ready for mass consumption. Marking on developer meeting as a PSA. Hopefully we can discuss how this function plays into our options strategy as part of the options/config design pattern discussion coming up.

**Comment by Denz1994** [comment] 2019-09-19 18:24
Discussed at dev meeting: 09/19/19

Merge() is fully operational and we can decide how to use this in the next software design pattern meeting.

Assigning to @jbphet to read through and close.

**Comment by jbphet** [comment] 2019-09-27 19:23
Thanks.  I've read through and ingested the information, and we can finalize how PhET uses `merge` in the next Software Design Pattern meeting (as @Denz1994 notes above).  Closing.

**Closed by jbphet** 2019-09-27 19:23 UTC
Labels: type:misc
