### ISSUE TITLE
Exalate option appears when creating new repo

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/phet-info#218] opened 2023-11-17 20:43 UTC
When creating a new repository for Projectile Data Lab, @samreid and I noticed the following option at the bottom of the new repo customization:

![Screen Shot 2023-11-17 at 3 41 58 PM](https://github.com/phetsims/phet-info/assets/108756567/c69c68ac-e94a-4353-bb61-f43bdfd64a73)

**Comment by matthew-blackman** [comment] 2023-11-17 20:45
Additional note: The Exalate checkbox is not able to be clicked, and is checked by default.

**Comment by samreid** [comment] 2023-11-17 20:46
Also I am seeing some Zenhub hooks?

![image](https://github.com/phetsims/phet-info/assets/679486/e4339793-40f7-4597-b555-a4b3a09d4fcb)

**Comment by marlitas** [comment] 2023-11-17 21:20
This seems to be resolved now:
<img width="1035" alt="image" src="https://github.com/phetsims/phet-info/assets/42476338/cd5fcc44-3b77-4764-8a8f-05a22b2b335e">

@samreid I did not see a zenhub webhook when I went to check...

**Comment by samreid** [comment] 2023-11-19 20:38
I confirmed the exalate option is gone, thanks! (It's not clear if someone did something explicit to address that). I deleted several zenhub hooks, but I didn't do a complete job and some are still around: https://github.com/phetsims/scenery-phet/settings/hooks.  Let's move that to a new issue and close this one.

**Closed by samreid** 2023-11-19 20:38 UTC
